/*
 * This file was automatically generated by CaffeineC.
 * Do not edit this file directly.
 */
#ifndef CAFFEINEC_H
#define CAFFEINEC_H
long printf(char * fmt);
long long testing();
char * malloc(long long size);
class SomeClass
{
private:
long long something;
public:
SomeClass();
void inc();
void dec();
long long get();
void set(long long newValue);
void add(long long toAdd);
void sub(long long toSub);
};
#endif
